#!/bin/bash

# PostgreSQL Migration Deployment Script
# EZBI Analytics Manufacturing Database
# Generated by Database Engineer

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="/var/log/ezbi_postgresql_migration.log"
BACKUP_DIR="/var/backups/ezbi_analytics"
CONFIG_FILE="${SCRIPT_DIR}/.env"

# Functions
log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] $1${NC}"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR $(date '+%Y-%m-%d %H:%M:%S')] $1${NC}" >&2
    echo "[ERROR $(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

warning() {
    echo -e "${YELLOW}[WARNING $(date '+%Y-%m-%d %H:%M:%S')] $1${NC}"
    echo "[WARNING $(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

info() {
    echo -e "${BLUE}[INFO $(date '+%Y-%m-%d %H:%M:%S')] $1${NC}"
    echo "[INFO $(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

check_prerequisites() {
    log "Checking prerequisites..."
    
    # Check if running as root for certain operations
    if [[ $EUID -ne 0 ]] && [[ "$1" != "test" ]]; then
        error "This script must be run as root for production deployment"
        exit 1
    fi
    
    # Check PostgreSQL installation
    if ! command -v pg_dump &> /dev/null; then
        error "PostgreSQL client tools not found. Please install postgresql-client"
        exit 1
    fi
    
    # Check Python and dependencies
    if ! command -v python3 &> /dev/null; then
        error "Python 3 not found. Please install Python 3.8+"
        exit 1
    fi
    
    # Check required Python packages
    python3 -c "import asyncpg, sqlalchemy, psutil" 2>/dev/null || {
        error "Required Python packages not installed. Run: pip install asyncpg sqlalchemy psutil"
        exit 1
    }
    
    log "Prerequisites check completed"
}

load_config() {
    log "Loading configuration..."
    
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
        log "Configuration loaded from $CONFIG_FILE"
    else
        warning "Configuration file not found. Using defaults."
        # Set default values
        export DB_HOST="${DB_HOST:-localhost}"
        export DB_PORT="${DB_PORT:-5432}"
        export DB_NAME="${DB_NAME:-ezbi_analytics}"
        export DB_USER="${DB_USER:-postgres}"
        export DB_PASSWORD="${DB_PASSWORD:-password}"
        export BACKUP_ROOT="${BACKUP_ROOT:-/var/backups/ezbi_analytics}"
        export ALERT_EMAIL="${ALERT_EMAIL:-admin@ezbi-analytics.com}"
    fi
    
    # Validate required variables
    if [[ -z "${DB_PASSWORD}" ]]; then
        error "DB_PASSWORD must be set"
        exit 1
    fi
    
    log "Configuration validated"
}

setup_directories() {
    log "Setting up directories..."
    
    # Create backup directories
    mkdir -p "$BACKUP_DIR"/{full,incremental,wal,logs}
    mkdir -p /tmp/ezbi_backup
    mkdir -p /var/log
    
    # Set permissions
    chown -R postgres:postgres "$BACKUP_DIR" 2>/dev/null || true
    chmod 755 "$BACKUP_DIR"
    
    log "Directories created successfully"
}

test_database_connection() {
    log "Testing database connection..."
    
    # Test connection with timeout
    timeout 10 pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" || {
        error "Cannot connect to PostgreSQL database"
        exit 1
    }
    
    # Test authentication
    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" > /dev/null || {
        error "Database authentication failed"
        exit 1
    }
    
    log "Database connection successful"
}

create_postgresql_extensions() {
    log "Creating PostgreSQL extensions..."
    
    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" << EOF
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;
EOF
    
    log "PostgreSQL extensions created"
}

run_migration() {
    log "Starting PostgreSQL migration..."
    
    # Run the migration script
    python3 "${SCRIPT_DIR}/postgresql_migration.py" || {
        error "Migration failed"
        exit 1
    }
    
    log "Migration completed successfully"
}

setup_monitoring() {
    log "Setting up monitoring..."
    
    # Create monitoring script
    cat > /usr/local/bin/ezbi_db_monitor.py << 'EOF'
#!/usr/bin/env python3
import sys
import os
sys.path.append('/path/to/your/project')
from postgresql_config import get_connection_pool
import asyncio
import json

async def main():
    pool = await get_connection_pool()
    health = await pool.health_check()
    print(json.dumps(health, indent=2, default=str))

if __name__ == "__main__":
    asyncio.run(main())
EOF
    
    chmod +x /usr/local/bin/ezbi_db_monitor.py
    
    # Create monitoring cron job
    echo "*/15 * * * * /usr/local/bin/ezbi_db_monitor.py >> /var/log/ezbi_db_health.log 2>&1" | crontab -
    
    log "Monitoring setup completed"
}

setup_backup_system() {
    log "Setting up backup system..."
    
    # Create backup script
    cp "${SCRIPT_DIR}/postgresql_backup_system.py" /usr/local/bin/ezbi_backup.py
    chmod +x /usr/local/bin/ezbi_backup.py
    
    # Create backup cron jobs
    cat > /tmp/ezbi_backup_cron << EOF
# EZBI Analytics Database Backup Jobs
0 2 * * * /usr/local/bin/ezbi_backup.py --action full-backup
0 */6 * * * /usr/local/bin/ezbi_backup.py --action incremental-backup
0 1 * * * /usr/local/bin/ezbi_backup.py --action cleanup
*/15 * * * * /usr/local/bin/ezbi_backup.py --action monitor
EOF
    
    crontab /tmp/ezbi_backup_cron
    rm /tmp/ezbi_backup_cron
    
    log "Backup system setup completed"
}

validate_migration() {
    log "Validating migration..."
    
    # Run validation script
    python3 << EOF
import asyncio
import sys
sys.path.append('${SCRIPT_DIR}')
from postgresql_migration import PostgreSQLMigrator, DatabaseConfig

async def validate():
    config = DatabaseConfig()
    async with PostgreSQLMigrator(config) as migrator:
        tables = migrator.get_manufacturing_tables()
        print(f"Found {len(tables)} manufacturing tables")
        
        for table in tables:
            validation = await migrator.validate_migration(table)
            if not validation['count_match'] or not validation['data_integrity']:
                print(f"VALIDATION FAILED for {table}")
                return False
        
        print("All validations passed")
        return True

if __name__ == "__main__":
    result = asyncio.run(validate())
    sys.exit(0 if result else 1)
EOF
    
    if [[ $? -eq 0 ]]; then
        log "Migration validation successful"
    else
        error "Migration validation failed"
        exit 1
    fi
}

create_rollback_script() {
    log "Creating rollback script..."
    
    cat > /usr/local/bin/ezbi_rollback.sh << EOF
#!/bin/bash
# EZBI Analytics PostgreSQL Rollback Script
# Generated: $(date)

set -euo pipefail

echo "WARNING: This will rollback the PostgreSQL migration!"
echo "Original SQLite database: ${SCRIPT_DIR}/data/ezbi_analytics.db"
echo ""
read -p "Are you sure you want to proceed? (type 'yes' to confirm): " confirm

if [[ "\$confirm" != "yes" ]]; then
    echo "Rollback cancelled"
    exit 0
fi

echo "Creating backup of current PostgreSQL state..."
pg_dump -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME > $BACKUP_DIR/pre_rollback_\$(date +%Y%m%d_%H%M%S).sql

echo "Dropping manufacturing tables..."
PGPASSWORD="$DB_PASSWORD" psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME << 'EOSQL'
DROP TABLE IF EXISTS sales_customers CASCADE;
DROP TABLE IF EXISTS sales_invoices CASCADE;
DROP TABLE IF EXISTS accounting_vendors CASCADE;
DROP TABLE IF EXISTS accounting_purchases CASCADE;
DROP TABLE IF EXISTS accounting_accounts_receivable CASCADE;
DROP TABLE IF EXISTS accounting_accounts_payable CASCADE;
DROP TABLE IF EXISTS operations_products CASCADE;
DROP TABLE IF EXISTS operations_production_orders CASCADE;
DROP TABLE IF EXISTS finance_cash_ledger CASCADE;
DROP TABLE IF EXISTS finance_debt_accounts CASCADE;
DROP TABLE IF EXISTS expenses_fixed_costs CASCADE;
DROP TABLE IF EXISTS hr_employees CASCADE;
DROP TABLE IF EXISTS hr_payroll_log CASCADE;
EOSQL

echo "Rollback completed. PostgreSQL manufacturing tables dropped."
echo "Original SQLite database is still available at: ${SCRIPT_DIR}/data/ezbi_analytics.db"
EOF
    
    chmod +x /usr/local/bin/ezbi_rollback.sh
    
    log "Rollback script created at /usr/local/bin/ezbi_rollback.sh"
}

generate_report() {
    log "Generating deployment report..."
    
    cat > "${SCRIPT_DIR}/deployment_report.json" << EOF
{
    "deployment_info": {
        "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
        "hostname": "$(hostname)",
        "user": "$(whoami)",
        "script_version": "1.0.0"
    },
    "database_config": {
        "host": "$DB_HOST",
        "port": "$DB_PORT",
        "database": "$DB_NAME",
        "user": "$DB_USER"
    },
    "directories_created": [
        "$BACKUP_DIR",
        "/tmp/ezbi_backup",
        "/var/log"
    ],
    "scripts_installed": [
        "/usr/local/bin/ezbi_db_monitor.py",
        "/usr/local/bin/ezbi_backup.py",
        "/usr/local/bin/ezbi_rollback.sh"
    ],
    "cron_jobs": [
        "Database monitoring (every 15 minutes)",
        "Full backup (daily at 2 AM)",
        "Incremental backup (every 6 hours)",
        "Cleanup (daily at 1 AM)"
    ],
    "status": "SUCCESS"
}
EOF
    
    log "Deployment report generated: ${SCRIPT_DIR}/deployment_report.json"
}

print_summary() {
    log "
=====================================
EZBI Analytics PostgreSQL Migration
=====================================

✅ Database migration completed successfully
✅ All 13 manufacturing tables migrated
✅ Connection pooling configured
✅ Backup system operational
✅ Monitoring system active
✅ Rollback procedures ready

Next Steps:
1. Update application configuration to use PostgreSQL
2. Restart application services
3. Monitor system performance
4. Test backup and recovery procedures

Important Files:
- Migration report: ${SCRIPT_DIR}/POSTGRESQL_MIGRATION_IMPLEMENTATION_REPORT.md
- Deployment report: ${SCRIPT_DIR}/deployment_report.json
- Backup logs: /var/log/ezbi_backup.log
- Health logs: /var/log/ezbi_db_health.log
- Rollback script: /usr/local/bin/ezbi_rollback.sh

Support:
- Database monitoring: /usr/local/bin/ezbi_db_monitor.py
- Manual backup: /usr/local/bin/ezbi_backup.py --action full-backup
- System status: tail -f /var/log/ezbi_backup.log

=====================================
"
}

main() {
    local action="${1:-deploy}"
    
    log "Starting EZBI Analytics PostgreSQL migration deployment..."
    
    case "$action" in
        "deploy")
            check_prerequisites
            load_config
            setup_directories
            test_database_connection
            create_postgresql_extensions
            run_migration
            setup_monitoring
            setup_backup_system
            validate_migration
            create_rollback_script
            generate_report
            print_summary
            ;;
        "test")
            check_prerequisites "test"
            load_config
            test_database_connection
            log "Test completed successfully"
            ;;
        "rollback")
            /usr/local/bin/ezbi_rollback.sh
            ;;
        "status")
            /usr/local/bin/ezbi_db_monitor.py
            ;;
        *)
            echo "Usage: $0 {deploy|test|rollback|status}"
            exit 1
            ;;
    esac
    
    log "Operation completed successfully"
}

# Run main function
main "$@"